name: Docker

on:  
  workflow_dispatch:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 12 * * *'

env:
  DOCKER_IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  cuda-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        #run: echo "::set-output name=matrix::{\"include\":[{\"img\":\"nvidia\/cuda:11.1-cudnn8-runtime-ubuntu20.04\",\"config\":\"Debug\"},{\"img\":\"bar\",\"config\":\"Release\"}]}"
        #run: echo "::set-output name=matrix::{\"img\":[\"nvidia\/cuda:11.1-cudnn8-runtime-ubuntu20.04\", \"asd\"]}"
        #run: strg=`cat cuda-strategy.json` && echo "::set-output name=matrix::${strg@Q}"
        run: strg=`cat strategy.json` && echo '::set-output name=matrix::'${strg}
      
  build:
    needs: cuda-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.cuda-tags.outputs.matrix)}}
    env:
      DOCKER_TAG: ${{ matrix.cuda }}-runtime-${{ matrix.os }}
    steps:
      - name: Tag
        run: echo $DOCKER_TAG

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'jupyter/docker-stacks'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
        # base-notebook
      - name: Docker meta
        id: docker_meta_base
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE_BASE }}/base-notebook
          tag-custom: ${{ env.DOCKER_TAG }}
          tag-custom-only: true

      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./base-notebook/
          file: ./base-notebook/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_base.outputs.tags }}
          labels: ${{ steps.docker_meta_base.outputs.labels }}
          build-args: |
            ROOT_CONTAINER=nvidia/cuda:${{ env.DOCKER_TAG }}
      
        # minimal-notebook
      - name: Docker meta
        id: docker_meta_minimal
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE_BASE }}/minimal-notebook
          tag-custom: ${{ env.DOCKER_TAG }}
          tag-custom-only: true

      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./minimal-notebook/
          file: ./minimal-notebook/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_minimal.outputs.tags }}
          labels: ${{ steps.docker_meta_minimal.outputs.labels }}
          build-args: |
            BASE_CONTAINER=${{ env.DOCKER_IMAGE_BASE }}/base-notebook
      
        # scipy-notebook
      - name: Docker meta
        id: docker_meta_scipy
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE_BASE }}/scipy-notebook
          tag-custom: ${{ env.DOCKER_TAG }}
          tag-custom-only: true

      - name: Build and push
        id: docker_build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./scipy-notebook/
          file: ./scipy-notebook/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_scipy.outputs.tags }}
          labels: ${{ steps.docker_meta_scipy.outputs.labels }}
          build-args: |
            BASE_CONTAINER=${{ env.DOCKER_IMAGE_BASE }}/minimal-notebook


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE_BASE }}/scipy-notebook:${{ steps.docker_meta_scipy.outputs.version }}
      
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
