name: Docker

on:  
  workflow_dispatch:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 12 * * *'

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  cuda-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        #run: echo "::set-output name=matrix::{\"include\":[{\"img\":\"nvidia\/cuda:11.1-cudnn8-runtime-ubuntu20.04\",\"config\":\"Debug\"},{\"img\":\"bar\",\"config\":\"Release\"}]}"
        #run: echo "::set-output name=matrix::{\"img\":[\"nvidia\/cuda:11.1-cudnn8-runtime-ubuntu20.04\", \"asd\"]}"
        #run: strg=`cat cuda-strategy.json` && echo "::set-output name=matrix::${strg@Q}"
        run: strg=`cat cuda-strategy.json` && echo '::set-output name=matrix::'${strg}
  build:
    needs: cuda-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.cuda-tags.outputs.matrix)}}
    env:
      IMAGE: ${{ matrix.cuda }}
    steps:
    - run: echo $IMAGE
